version: '3.8'
services:
  db1:
    image: postgres:13
    container_name: postgres_db1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
  db2:
    image: postgres:13
    container_name: postgres_db2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
volumes:
  postgres_data1:
  postgres_data2: