version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  simulador:
    build: ./main
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=banco
      - DB_USER=mi_usuario
      - DB_PASSWORD=mi_clave
    command: ["python", "script.py", "60"]  # Ejecuta el script por 60 segundos

volumes:
  db_data:
